### PR TITLE
#367 - change apartment number

### LINKED ISSUE #367: After hiding tag in news there is 500 error but only on beta
On beta environment I noticed a bug but I can't reproduce it locally.

Steps to reproduce:
- Go to "News" tab and choose tag "Rozwój"
- See all post related to tag "Rozwój"
- Open new car with admin panel; 
- in "Tags" tab, uncheck option "Oznacz jako główny" next to "Rozwój tag"
- Refresh page with news related to "Rozwój" tag
- see 500 error

When Sentry (issue #359) will be added I think it will really help to fix this

### PR DESCRIPTION
**Pull request by EwelinaSkrzypacz**
Due to Kasia request, I change apartment number -> from 5F/5 to 5F/3

Also I fixed things requested by Kasia:
- change color of button "Zobacz więcej projektów"
- change top padding on "O firmie" page
- change title to be in one line on homepage

And with a big help @Baakoma we fixed #367.

### CODE REVIEW

File: lang/en/content.php [hunk 1]
```diff
@@ -256,7 +256,7 @@
             "text_2" => "Blumilk sp. z o.o.,",
             "text_3" => "with its registered office in Legnica, entered by the District Court for Wrocław-Fabryczna in Wrocław, 9th Commercial Division, into the register of entrepreneurs of the National Court Register under the number 0000866755.",
             "text_4" => "Official address: Blumilk Sp. z o. o., ul. rtm. Witolda Pilecki 14, 59-220 Legnica, Poland.",
-            "text_5" => "Office address: Blumilk Sp. z o. o., ul. Najściej Marii Panny 5F/5, 59-220 Legnica, Poland.",
+            "text_5" => "Office address: Blumilk Sp. z o. o., ul. Najściej Marii Panny 5F/3, 59-220 Legnica, Poland.",
```
Comment (vojcc) [inline lang/en/content.php:259]:
```suggestion
            "text_5" => "Office address: Blumilk Sp. z o. o., ul. Najświętszej Marii Panny 5F/3, 59-220 Legnica, Poland.",
```

**Review by dawidrudnik — APPROVED** [review]

**Review by MichalMyskow — APPROVED** [review]
